# Generated by Django 5.1.1 on 2024-12-11 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_rename_transations_type_transactions_transactions_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='transfer_account_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
