# Generated by Django 5.1.1 on 2024-12-12 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_transactions_transfer_account_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='transfer_account_no',
        ),
        migrations.AlterField(
            model_name='transactions',
            name='transactions_type',
            field=models.IntegerField(choices=[(1, 'Deposite'), (2, 'Withdrawal'), (3, 'Loan'), (4, 'Loan Paid'), (5, 'Transter money'), (6, 'Receive money')], null=True),
        ),
    ]
