# Generated by Django 5.1.1 on 2024-12-13 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_remove_transactions_transfer_account_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='is_bankrupt',
            field=models.BooleanField(default=False),
        ),
    ]
