# Generated by Django 5.1.1 on 2024-12-13 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_transactions_is_bankrupt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='is_bankrupt',
        ),
    ]
